from dataclasses import dataclass
@dataclass
class DataIngestionArtifact:
    feature_store_file_path:str
    train_file_path:str 
    test_file_path:str
class DataValidationArtificat:...
class DataTransformationArtificat:...
class ModelTrainingArtificat:...
class ModelEvaluateArtificat:...
class ModelPusherArtificat:...