class DataIngestionArtificat:...
class DataValidationArtificat:...
class DataTransformationArtificat:...
class ModelTrainingArtificat:...
class ModelEvaluateArtificat:...
class ModelPusherArtificat:...